repos:
-   repo: local
    hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [python]
-   repo: local
    hooks:
    - id: ruff
      name: ruff
      entry: poetry run ruff
      language: system
      types: [python]
-   repo: local
    hooks:
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [python]
-   repo: local
    hooks:
    - id: interrogate
      name: interrogate
      entry: poetry run interrogate
      language: system
      types: [python]
      args: [src, -v, -i]
